GET http://localhost:3000/api/inmuebles

###
POST http://localhost:3000/api/inmuebles
Content-Type: application/json

{
    "piso": 5,
    "letra": "A",
    "extension_m2": 100,
    "numero_habitaciones": 2,
    "alquilado": false,
    "nombre_propietario": "Norma Herrera",
    "mail_contacto": "herrera.n@gmail.com"
}

###
PUT http://localhost:3000/api/inmuebles/635eb2295d8ce7bf04a249e7
Content-Type: application/json

{
   "piso": 0
}


###
DELETE http://localhost:3000/api/inmuebles/635eb14dcae0e99ab2d24c98
